### ISSUE TITLE
missing data in ALL_PATHS_featuretable.csv

### ISSUE THREAD

**Issue by wrystal** [SAWassermann/NETPerfTrace#2]
Sorry to bother, it seems that your given file misses data for the last day (the last time slot) of each path. 

That is to say, the column `totalNbRouteChanges` and `currentNbRouteChangesnSlot`  in `ALL_PATHS_featuretable.csv` , there are only 6 time slots for each path (indicated from `currentNbRouteChangesnSlot`) and if adding up numbers of route-change in each slot does not satisfy what is given in  corresponding `totalNbRouteChanges`.

Or maybe it is my misunderstanding :(

**Comment by SAWassermann** [comment]
Hi @wrystal ,

If I understood your question correctly, the numbers are correct, but maybe not obvious to grasp.

`currentNbRouteChangesInSlot` defines the number of currently seen route changes in each timeslot separately, while `totalNbRouteChanges` takes into account all the route changes over all timeslots.
Concretely, this means that `totalNbRouteChanges` also considers the route changes which happen "in-between" consecutive timeslots, which are not counted in `nbRouteChangesInSlot`.
The following figure illustrates this better:
![netperftrace](https://user-images.githubusercontent.com/7100794/33937475-fa50980e-e003-11e7-8b95-0b9d618bfc19.png)

In this case, you can see that the route change A -> C is not counted in any timeslot, as it does not really happen in one timeslot, but when changing timeslots. So at the end, you have indeed that `nbRouteChangesInSlot` in timeslot 1 + `nbRouteChangesInSlot` in timeslot 2 != `totalNbRouteChanges`.

Is it a bit clearer now?

**Comment by wrystal** [comment]
Thanks a lot for your explanation. It seems clearer to me now. But I still have a question, is there a time interval between two time slots? If not, since there are only 6 time slots (observed from the data) provided in the csv file, the relataionship between `totalNbRouteChanges` and `nbRouteChangesInSlot`  should be something similiar to
>  `totalNbRouteChanges`  -  (`nbRouteChangesInSlot` in timeslot 1 + `nbRouteChangesInSlot` in timeslot 2 + ... + `nbRouteChangesInSlot` in timeslot 6) = 5 

Is that correct? But the difference I found in the data is often lager than `5` .

**Comment by SAWassermann** [comment]
Yes, you are right.
There is no time interval between two timeslots.
The problem is the following:
One of the prediction targets in our paper was `nbRouteChangesInNextSlot` (i.e. the number of route changes in the **next** timeslot). This implied that the file you are currently looking at contains, for each path, only 6 timeslots/days and not 7 (one week), because, for the 7th timeslot, there was no value for `nbRouteChangesInNextSlot` (as we only looked at one week of data, so no 8th timeslot). At the end, you can indeed have a difference larger than 5, as  `totalNbRouteChanges`takes into account the number of changes from all the 7 timeslots, while the samples you see are only for the 6 first timeslots.

I hope my explanation makes sense.

**Comment by wrystal** [comment]
I thought you would provide with the whole 7 days/timeslots data instead of 6. And this was the point. 

Thanks for explanation. I have made it clear :)

**Comment by SAWassermann** [comment]
You are welcome!
We released all the samples that could be used for our prediction targets :)
